# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go generate ./...
builds:
  - main: .
    binary: longshiplink-auth
    ldflags:
      - -s
      - -w
      - -extldflags
      - -static
      #- -X main.Commit={{.Commit}}
      #- -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - riscv64
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^deployments:'